// examples/vue-example/src/components/LanguageSwitcher.vue
<template>
  <div>
    <button @click="setLanguage('en')">English</button>
    <button @click="setLanguage('fr')">Français</button>
  </div>
</template>

<script>
import { useI18n } from 'rosettajs-i18n';

export default {
  name: 'LanguageSwitcher',
  setup() {
    const { setLanguage } = useI18n();
    return { setLanguage };
  }
}
</script>

// examples/preact-example/src/components/LanguageSwitcher.tsx
import { h } from 'preact';
import { usePreactTranslation } from 'rosettajs-i18n';

export default function LanguageSwitcher() {
  const { setLanguage } = usePreactTranslation();

  return (
    <div>
      <button onClick={() => setLanguage('en')}>English</button>
      <button onClick={() => setLanguage('fr')}>Français</button>
    </div>
  );
}
